### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by hurfy** [MafiaHub/MafiaMP#18]
Archive

**Comment by hurfy** [comment]
![betting_office](https://user-images.githubusercontent.com/46726909/189526129-a844a92d-b887-473a-9b42-0b533bd24714.jpg)
![bolt_truck_scripted_farm1201](https://user-images.githubusercontent.com/46726909/189526132-74473546-2754-4a08-b81a-87f01ba6f7a2.jpg)
![bolt_truck_scripted_farm1202](https://user-images.githubusercontent.com/46726909/189526133-6b6a830b-cfbe-4375-be95-f5e9014052b8.jpg)
![bolt_truck_scripted_farm1203](https://user-images.githubusercontent.com/46726909/189526134-0d0bfaa8-e815-4575-8ca3-9df36f49c332.jpg)
![bolt_truck_scripted_farm1204](https://user-images.githubusercontent.com/46726909/189526139-e6c3db3e-5894-4cdc-9b8e-86a3e9904c7a.jpg)
![bolt_truck_scripted_farm1205](https://user-images.githubusercontent.com/46726909/189526149-c5de3632-c4af-48e6-ac24-9859de751f56.jpg)
![bolt_truck1201](https://user-images.githubusercontent.com/46726909/189526154-9ea53a9e-238b-43d1-9c0f-1d8cf484ef9b.jpg)
![bolt_truck1202](https://user-images.githubusercontent.com/46726909/189526156-cd03f663-b253-4482-94cb-7852e4e79e94.jpg)
![bolt_truck1203](https://user-images.githubusercontent.com/46726909/189526160-9373a6f7-96f2-40fe-9b5b-fe2560580042.jpg)
![bolt_truck1204](https://user-images.githubusercontent.com/46726909/189526164-5882e286-f16f-4677-a7fc-8f9f1c34f6b8.jpg)
![bolt_truck1205](https://user-images.githubusercontent.com/46726909/189526170-c94be68d-c79e-4b48-99d1-3296a25bca8f.jpg)
![box_trailer](https://user-images.githubusercontent.com/46726909/189526176-c1ebb447-b3e7-4ff1-8917-83db3d888a7d.jpg)
![bulworth_packhard](https://user-images.githubusercontent.com/46726909/189526178-d322c86a-c848-4855-a3e9-7e5dd92f81b3.jpg)
![bulworth_sentry](https://user-images.githubusercontent.com/46726909/189526181-25b2ab56-356d-4681-adf8-5765b6228883.jpg)
![hank_a](https://user-images.githubusercontent.com/46726909/189526184-f3fdbcf1-b691-4d25-aeb1-fa13a18cf5da.jpg)
![parry_bus1201](https://user-images.githubusercontent.com/46726909/189526186-7f6d3e98-a290-4cf4-81cf-b6829b0a7c5a.jpg)
![parry_bus1202](https://user-images.githubusercontent.com/46726909/189526188-d2ffb48a-a2fe-48d3-bb52-ecf391c9bc30.jpg)
![parry_bus1203](https://user-images.githubusercontent.com/46726909/189526192-52751d70-b7ca-4cf7-ba95-1d3ecd0391bc.jpg)
![samson_tanker](https://user-images.githubusercontent.com/46726909/189526196-ee61b0c0-5673-44df-ade0-3cfcc0117fa9.jpg)

**Comment by hurfy** [comment]
![lassiter_v16_roadster501](https://user-images.githubusercontent.com/46726909/189526257-3aaa52f8-3fed-4dc0-84ef-a8302295cd07.jpg)
![lassiter_v16_roadster503](https://user-images.githubusercontent.com/46726909/189526265-f441bac0-e423-4b57-91f2-973220e87574.jpg)
![manta_prototype](https://user-images.githubusercontent.com/46726909/189526270-b3dd5c04-996b-44ea-b501-f63311e33702.jpg)
![mutagen](https://user-images.githubusercontent.com/46726909/189526276-0c5ec334-4bed-4070-875b-81539480b8ca.jpg)
![samson_drifter](https://user-images.githubusercontent.com/46726909/189526296-adc1ac2b-86ce-4ad4-98e1-f3e379c652ac.jpg)
![shubert_e_six](https://user-images.githubusercontent.com/46726909/189526307-bdddedd6-eba8-4a4e-8086-e96c75e1bb81.jpg)
![shubert_e_six_det](https://user-images.githubusercontent.com/46726909/189526316-94cb32ad-7cd4-4c07-9498-de2bad0277ed.jpg)
![shubert_e_six_det1201](https://user-images.githubusercontent.com/46726909/189526327-63bab988-69dd-47be-8969-92cb39969418.jpg)
![shubert_e_six_det1202](https://user-images.githubusercontent.com/46726909/189526340-a0f43c92-09a7-4069-ab11-8e7c8bdcfcd3.jpg)
![shubert_e_six_det1203](https://user-images.githubusercontent.com/46726909/189526356-303fe1c6-2001-4cde-acb2-c39bcc4990e4.jpg)
![shubert_e_six_p](https://user-images.githubusercontent.com/46726909/189526368-158f5b40-388e-480f-847c-9911d3df2a20.jpg)
![shubert_e_six_p1201](https://user-images.githubusercontent.com/46726909/189526378-855bba8f-4670-46b0-bddc-cda4f7b9ec7c.jpg)
![shubert_e_six_p1202](https://user-images.githubusercontent.com/46726909/189526389-1d9c576e-15e3-49d2-be49-4e07dd09c8f4.jpg)
![shubert_e_six_p1203](https://user-images.githubusercontent.com/46726909/189526395-bbf3236e-fad8-4abd-96d1-d471c1ca2c35.jpg)
![shubert_e_six_taxi](https://user-images.githubusercontent.com/46726909/189526405-6ad93798-e537-45d1-a48a-bd1609fdf462.jpg)
![shubert_e_six_taxi1201](https://user-images.githubusercontent.com/46726909/189526429-e3bf920e-8ea5-4997-b95d-4ef5a55483bf.jpg)
![shubert_e_six_taxi1202](https://user-images.githubusercontent.com/46726909/189526438-a50591e8-4676-441d-a0d4-63a366b07c98.jpg)
![shubert_e_six_taxi1203](https://user-images.githubusercontent.com/46726909/189526451-7fecc94c-917e-4e0b-ba47-b35ce654b072.jpg)
![shubert_e_six_taxi1204](https://user-images.githubusercontent.com/46726909/189526499-554eef82-ed8e-492c-8576-9809649ec306.jpg)
![shubert_e_six1201](https://user-images.githubusercontent.com/46726909/189526516-cf3dbdda-9c75-46dc-a52f-df4457a710c5.jpg)
![shubert_e_six1202](https://user-images.githubusercontent.com/46726909/189526529-ceb3d2e3-9380-4f2b-aa9d-2b0709aac651.jpg)
![shubert_e_six1203](https://user-images.githubusercontent.com/46726909/189526544-4ac859c7-8a60-49d3-9bac-6e774f721282.jpg)
![shubert_frigate](https://user-images.githubusercontent.com/46726909/189526554-166b6d9b-d0c8-4fdd-bdb5-1c6f292e9436.jpg)
![shubert_six](https://user-images.githubusercontent.com/46726909/189526559-26ea972d-c59a-460a-9699-3f9390483940.jpg)
![shubert_six_det](https://user-images.githubusercontent.com/46726909/189526574-e007783d-ac02-4a8d-9c4e-86ae7bf4dd41.jpg)
![shubert_six_det1201](https://user-images.githubusercontent.com/46726909/189526583-1bb841a8-5b53-4b07-9693-4ea23042179d.jpg)
![shubert_six_det1202](https://user-images.githubusercontent.com/46726909/189526593-d28f32ae-3203-44a5-8944-9fbe0542647a.jpg)
![shubert_six_p](https://user-images.githubusercontent.com/46726909/189526600-9fa24df4-6d7d-4685-9d9c-f3d2952c665d.jpg)
![shubert_six_p1201](https://user-images.githubusercontent.com/46726909/189526615-01bc1e89-e7ca-4ca4-8404-d2b27dc288cb.jpg)
![shubert_six_p1202](https://user-images.githubusercontent.com/46726909/189526624-8e7fa457-271f-480d-8d8e-1e0f6fbf9d31.jpg)
![shubert_six_taxi](https://user-images.githubusercontent.com/46726909/189526630-70d4ba1a-30c7-497e-a105-dd2d43955bf8.jpg)
![shubert_six_taxi1201](https://user-images.githubusercontent.com/46726909/189526646-8e35a621-71c1-44ca-8b02-05505908cb00.jpg)
![shubert_six_taxi1202](https://user-images.githubusercontent.com/46726909/189526650-c7688bb3-dc60-49d4-8d03-eac5f60935ec.jpg)
![shubert_six1201](https://user-images.githubusercontent.com/46726909/189526660-a15bb81e-c06a-4f1e-8429-d6acc83c13fe.jpg)
![shubert_six1202](https://user-images.githubusercontent.com/46726909/189526669-789bbb1e-5b07-48eb-a542-8ce7f2518e1c.jpg)
![smith_moray1101](https://user-images.githubusercontent.com/46726909/189526685-9a265145-e4eb-4aa8-8d15-f80a40ac4314.jpg)
![smith_moray1102](https://user-images.githubusercontent.com/46726909/189526691-117cfc86-7f7e-4a20-896f-6520446c5e7f.jpg)
![smith_moray1103](https://user-images.githubusercontent.com/46726909/189526707-6878eef8-64a1-4f13-903d-dc8f39cc9cbf.jpg)
![smith_thrower](https://user-images.githubusercontent.com/46726909/189526714-1a50d840-c09c-48ac-a282-bc9673bbb43d.jpg)
![smith_v12_chicago1101](https://user-images.githubusercontent.com/46726909/189526725-af1d4a62-5a15-46d7-9080-852d8aa5dc6f.jpg)
![smith_v12_chicago1102](https://user-images.githubusercontent.com/46726909/189526737-d989d892-1352-4cd6-af38-4c00719d6ddb.jpg)
![smith_v12_chicago1103](https://user-images.githubusercontent.com/46726909/189526758-5cd08190-7480-44c7-934b-cfe76474c112.jpg)
![smith_v121101](https://user-images.githubusercontent.com/46726909/189526771-643e4640-7a08-4c26-a1ad-df01043a2a48.jpg)
![smith_v121102](https://user-images.githubusercontent.com/46726909/189526785-e0ac36b0-d09a-48ea-9c74-60e9f7c21d74.jpg)
![smith_v121103](https://user-images.githubusercontent.com/46726909/189526796-779cf136-19f0-4af5-a1aa-697581f72eed.jpg)
![trautenberg_sport1101](https://user-images.githubusercontent.com/46726909/189526806-04fd6f28-9ee2-4d50-bb9b-5d4e043aeb15.jpg)
![trautenberg_sport1102](https://user-images.githubusercontent.com/46726909/189526827-c7c86da1-a172-4622-bfbe-639e492044dc.jpg)
![trautenberg_sport1103](https://user-images.githubusercontent.com/46726909/189526845-ff774237-8de8-40bd-a2c4-2eda0e9784bd.jpg)

**Comment by hurfy** [comment]
![bolt_ace_pickup](https://user-images.githubusercontent.com/46726909/189528617-841d6e33-6e32-4869-8987-d3f7fc9d3ddc.jpg)
![bolt_ace_pickup1201](https://user-images.githubusercontent.com/46726909/189528626-95fce4a3-753c-47fe-81b6-7d4eddada77c.jpg)
![bolt_ace_pickup1202](https://user-images.githubusercontent.com/46726909/189528631-cb41f78e-2698-42b7-a380-c929a28e8c22.jpg)
![bolt_ace_pickup1203](https://user-images.githubusercontent.com/46726909/189528637-4e7ed14d-0ca8-4d38-9eb2-bdea1b2a4810.jpg)
![bolt_ace1101](https://user-images.githubusercontent.com/46726909/189528642-2c69c60c-4e0e-41db-8a3a-6e7f5b75c569.jpg)
![bolt_ace1102](https://user-images.githubusercontent.com/46726909/189528645-cc75542f-b7c3-44c1-8ead-824c5eecd00a.jpg)
![bolt_ace1103](https://user-images.githubusercontent.com/46726909/189528649-ef021f24-b40e-4b7d-bc01-53160554a90f.jpg)
![berkley_810](https://user-images.githubusercontent.com/46726909/189528653-32e298f6-29ce-47c2-af79-6c6c9f9fae41.jpg)
![bolt_cooler](https://user-images.githubusercontent.com/46726909/189528663-b413edd0-c935-492c-8e41-62b760916aed.jpg)
![bolt_delivery](https://user-images.githubusercontent.com/46726909/189528668-55ee1bcd-eb17-4d54-8739-be699ab39199.jpg)
![bolt_delivery_amb](https://user-images.githubusercontent.com/46726909/189528673-81ba21f1-07cf-422c-8bf3-1e17c0029e77.jpg)
![bolt_hearse](https://user-images.githubusercontent.com/46726909/189528681-52a8af2b-7004-4e88-82d1-f14d788e704e.jpg)
![bolt_hearse1201](https://user-images.githubusercontent.com/46726909/189528688-28aa5a49-c30f-4190-8dfc-2ef795988b13.jpg)
![bolt_hearse1202](https://user-images.githubusercontent.com/46726909/189528695-04662215-8975-430c-801e-cda7995989e6.jpg)
![bolt_mail](https://user-images.githubusercontent.com/46726909/189528701-2478accd-9c00-4c50-abca-7e48f6aa2098.jpg)
![bolt_model_b1101](https://user-images.githubusercontent.com/46726909/189528717-f5606792-2099-41c5-a878-151d867bb3da.jpg)
![bolt_model_b1102](https://user-images.githubusercontent.com/46726909/189528720-083869a8-e2db-4193-9a75-c07e0d1f921a.jpg)
![bolt_model_b1103](https://user-images.githubusercontent.com/46726909/189528728-027339a8-7215-45a5-9f46-80995257a806.jpg)
![bolt_model_b1201](https://user-images.githubusercontent.com/46726909/189528731-e3d61a1c-aced-4489-bcb9-c9ef829eeeee.jpg)
![bolt_model_b1202](https://user-images.githubusercontent.com/46726909/189528735-08d6c826-a212-4855-abc3-e32adbdb7622.jpg)
![bolt_pickup1201](https://user-images.githubusercontent.com/46726909/189528746-7bd06a12-d531-4268-80d2-3c63dc12606d.jpg)
![bolt_pickup1202](https://user-images.githubusercontent.com/46726909/189528758-7adf0efc-0f1b-450e-939b-1ed9dcc7f68d.jpg)
![bolt_pickup1203](https://user-images.githubusercontent.com/46726909/189528772-73f50f91-a053-4d05-b498-f6e8fa01713e.jpg)
![bolt_pickup1204](https://user-images.githubusercontent.com/46726909/189528778-4721997a-ead1-4048-96e2-329c768eface.jpg)
![bolt_pickup1205](https://user-images.githubusercontent.com/46726909/189528782-31784153-5bfe-4035-9686-927bfe421ab2.jpg)
![bolt_pickup1206](https://user-images.githubusercontent.com/46726909/189528786-fe08ae64-175e-4075-98cd-45c33f3a295f.jpg)
![bolt_v81101](https://user-images.githubusercontent.com/46726909/189528797-0622aa16-84f7-4b54-b027-d4b449177bbb.jpg)
![bolt_v81102](https://user-images.githubusercontent.com/46726909/189528810-a6d1578f-f7bf-4cf7-a4ec-29e6b3e593f1.jpg)
![bolt_v81103](https://user-images.githubusercontent.com/46726909/189528817-9c055d2b-4a21-4c36-a550-f00beba7e83a.jpg)
![brubaker_forte](https://user-images.githubusercontent.com/46726909/189528824-76f79a83-db46-4567-aa24-d7e8c2ba5648.jpg)
![celeste_mark_51101](https://user-images.githubusercontent.com/46726909/189528833-09a59d0d-a300-4a1d-8640-51a83813fcb5.jpg)
![celeste_mark_51102](https://user-images.githubusercontent.com/46726909/189528841-961d03f4-dc06-43d2-a011-fa0ee72844e1.jpg)
![celeste_mark_51103](https://user-images.githubusercontent.com/46726909/189528848-d8930847-2c35-4cfe-9c20-0cfca8c62091.jpg)
![crazy_horse](https://user-images.githubusercontent.com/46726909/189528854-33e81088-b784-4ca4-95f1-f90ab32e1b8d.jpg)
![culver_airmaster](https://user-images.githubusercontent.com/46726909/189528866-1495821e-1589-48f1-a9f2-e0cf11feb675.jpg)
![disorder](https://user-images.githubusercontent.com/46726909/189528870-6a7f0dff-9384-4b18-b465-f69758797c22.jpg)
![eckhart_crusader](https://user-images.githubusercontent.com/46726909/189528880-4b83f74d-86c0-480f-ac4e-a0664ac8b7ed.jpg)
![eckhart_elite](https://user-images.githubusercontent.com/46726909/189528884-4e8f9113-be15-4b78-9a51-e924f1cc9d69.jpg)
![eckhart_fletcher](https://user-images.githubusercontent.com/46726909/189528888-908a9f5d-ad70-443f-9ab7-f3e5269e7dd5.jpg)
![falconer_classic](https://user-images.githubusercontent.com/46726909/189528902-b798ea1d-e63d-4d55-afa4-ba4d886c0657.jpg)
![flame_spear](https://user-images.githubusercontent.com/46726909/189528907-ce4e4093-6902-4844-8421-6e9e2392fe06.jpg)
![houston_coupe1101](https://user-images.githubusercontent.com/46726909/189528915-d32ae97b-6ca5-439a-bee3-670e6aea9ad4.jpg)
![houston_coupe1102](https://user-images.githubusercontent.com/46726909/189528922-a3110c79-4617-4452-94e0-133f1fef9dc8.jpg)
![houston_coupe1103](https://user-images.githubusercontent.com/46726909/189528928-e8ee3e12-47f3-4f3b-a7d0-f6519d0e7d44.jpg)
![lassiter_v16](https://user-images.githubusercontent.com/46726909/189528939-fa69e91d-2ca6-495e-a590-1586f0ab59d9.jpg)
![lassiter_v16_appolyon1101](https://user-images.githubusercontent.com/46726909/189528993-1cbd7558-a63e-4f10-a878-08fcc945a545.jpg)
![lassiter_v16_appolyon1102](https://user-images.githubusercontent.com/46726909/189528995-cdcd5e1d-a840-4ed7-9d07-afcbfbf096ab.jpg)
![lassiter_v16_appolyon1103](https://user-images.githubusercontent.com/46726909/189528996-a04deef8-a78d-48aa-9c73-f8dfc9356e52.jpg)

**Comment by hurfy** [comment]
![suspension](https://user-images.githubusercontent.com/46726909/190880786-d52cb69c-e72a-44a5-a396-85123e65f0ae.gif)

**Comment by zpl-zak** [comment]
Closing this one so it doesn't show up in issues, but we can keep using it for assets.
