### ISSUE TITLE
Handle respawn

### ISSUE THREAD

**Issue by Segfaultd** [MafiaHub/MafiaMP#19]
Player death hook is ready, so now we have to notify the server.

Then, it's up to the server to control what to do. We could add a message for respawn that takes a position and when received on client, fade in - out the screen and apply the respawn position then sets the health to max.

The following tasks need to be covered:
- [x] let server handle death event
- [x] ensure we can set local player transform
- [x] ensure we can perform fadein/out via ingame UI helpers

**Comment by zpl-zak** [comment]
The following tasks need to be covered:
- [x] let server handle death event
- [ ] ensure we can set local player transform
- [ ] ensure we can perform fadein/out via ingame UI helpers

**Comment by zpl-zak** [comment]
Done
