### ISSUE TITLE
About in-game Radio

### ISSUE THREAD

**Issue by Deewarz** [MafiaHub/MafiaMP#34]
# EDIT: Season have no impact on radio. They are always the same regardless of the period. Season impact traffic only. (vehicles)

_Related to MR https://github.com/MafiaHub/MafiaMP/pull/30_

# Context

The sound/playlist of the radio depends on the `Season`.

A `Season` corresponds to an era in the game, as follows:
- -1 => No season
- 1 => Year 1930
- 2 => Year 1932
- 3 => Year 1933
- 4 => Year 1935
- 5 => Year 1938
- 100 => Freeride

This tells the game to populate the world with vehicles, NPCs and radio playlists corresponding to the chosen era.

# Problem

**If no `Season` is chosen then there is no associated playlist, the radio is therefore useless.**

Currently, we deactivate the function that allows anyone to set the `Season` here:  https://github.com/MafiaHub/MafiaMP/blob/master/code/client/src/core/hooks/traffic.cpp#L5

Therefore, the game does not activate any `Season` (instead of activating `100` by default).

# Possible solution

Do not disable the entire `Season` but simply the generation of vehicles and NPCs. (or sync everything!! haha)
No idea how to do this at the moment....

# See Also

Helpful Lua code

```lua
print("Initial Season")
local initialSeasonID = game.traffic:GetCurrentSeasonID()
print(initialSeasonID)

-- Always close the current season before opening another.
print("Close Season")
game.traffic:CloseSeason()

print("Open Season 3 (Year 1933)")
game.traffic:OpenSeason(3)

print("New Season")
local newSeasonID = game.traffic:GetCurrentSeasonID()
print(newSeasonID)
```

**Comment by Kamzik123** [comment]
It is possible to disable spawning of traffic, both vehicles and NPCs with these functions. However, it does not disable all vehicle spawners, namely the ones in the street right next to Salieri's bar.

```lua
game.traffic:CloseSeason() -- Not strictly necessary, but in rare occasions some vehicles remained spawned when the season was left open
game.traffic:SetEnableAmbientTrafficSpawning(false)
game.traffic:SetMaxHumanElements(0)
game.traffic:SetMaxVehicleElements(0,0,0,0,0,0)
game.traffic:SetTrainDensity(0)
game.police:Disable() -- Police vehicles and NPCs do not get affected by the previous traffic functions
game.traffic:OpenSeason(1)
```

**Comment by Deewarz** [comment]
I was wrong about this one, i'm sorry.
After digging through IDA and doing some testing, the season has no impact on radio in MDE. 

Description edited and issue closed.
