### ISSUE TITLE
Car duplication on gamemode reload

### ISSUE THREAD

**Issue by zpl-zak** [MafiaHub/MafiaMP#38]
## Problem
Upon gamemode reload, we spawn new batch of parked vehicles, however we do not despawn existing ones yet.

## Solution
Leverage `gamemodeUnloading` event to despawn all parked vehicles in our sample gamemode script.

Call `car.destruct()` to remove entity.

**Comment by Deewarz** [comment]
I wonder if this shouldn't be done automatically by the server rather than the scripter?

What's the benefit?

**Comment by zpl-zak** [comment]
Server does not know which entities were spawned by the gamemode itself.

**Comment by zpl-zak** [comment]
Put on hold, different solution will be implemented.
