### ISSUE TITLE
SDK::GetPlayerTeleportModule()->TeleportPlayer fails to teleport local player

### ISSUE THREAD

**Issue by zpl-zak** [MafiaHub/MafiaMP#45]
Used in https://github.com/MafiaHub/MafiaMP/blob/4bcbf1150a1bf3aae86e1901e0d08f8d4241dc3b/code/client/src/core/modules/human.cpp#L495

### Issue Description

- The `TeleportPlayer` function is not working properly for the local player.
- Instead of teleporting the player, it alters the player's viewing direction.
- The function erroneously takes a position value for the direction parameter.

### Action Items

- [ ] Correct the `teleport player` function to actually teleport the player to the specified position.
- [ ] Adjust the code to correctly extract and pass the player's direction based on their orientation.
    - [ ] Use either the rotation quaternion or the transformation matrix to obtain the correct direction value.
- [ ] Test the updated `teleport player` function to ensure it properly teleports the player without side effects.

### Summary

- The local player's teleportation feature is currently malfunctioning.
- Misuse of a position value for the direction is resulting in incorrect behavior.
- Fixing these issues will enable proper player teleportation and functional integration with the scripting engine.

**Comment by Deewarz** [comment]
FYI: I think the third param is the Direction

**Comment by zpl-zak** [comment]
Correct, the third param needs to be calculated from rotation. Still,
actual teleport does not happen sadly.

On January 11, 2024, Deewarz ***@***.***> wrote:
> FYI: I think the third param is the Direction
>

—
Reply to this email directly, view it on GitHub
<https://github.com/MafiaHub/MafiaMP/issues/45#issuecomment-1887891361>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/ACE3ZYTPFJX6RQ5QQEHI3BDYOBBTBAVCNFSM6AAAAABBXBG2W6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBXHA4TCMZWGE>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
