### ISSUE TITLE
Override JS player/vehicle GetScale/SetScale methods to only use scalar float

### ISSUE THREAD

**Issue by zpl-zak** [MafiaHub/MafiaMP#49]
### Issue Description
- The current framework codebase uses a Vector3 structure to specify the scale of entity.
- MafiaMP relies on a scalar floating point value for model scale, which means it uses uniform scaling.

### Action Items
- [ ] Override the `setScale` and `getScale` functions within the scripting engine to operate only with scalar floating point values.
- [ ] Reuse one of the Vector3's three components as a storage for the scalar value.
- [ ] Ensure that MafiaMP applies the scalar value directly on the client side via an SDK call to scale the entity properly.

**Comment by Deewarz** [comment]
Check if natives are right:
- https://github.com/MafiaHub/MafiaMP/blob/6be75b20657e8597828fb11438eb16be5006ff14/code/client/src/sdk/entities/c_actor.h#L21
-https://github.com/MafiaHub/MafiaMP/blob/6be75b20657e8597828fb11438eb16be5006ff14/code/client/src/sdk/entities/c_actor.h#L16
