### ISSUE TITLE
Rethink debug UIs

### ISSUE THREAD

**Issue by Deewarz** [MafiaHub/MafiaMP#87]
- Move debug UIs in a dedicated folder
- Add support for disabling controls for all debug UIs (like for Console)
- Create a base class for all UI to manage visibility, cursor, blocked controls...
- Make the background transparent when the UI has no focus (like for Console)

**Comment by Segfaultd** [comment]
We should probably merge all debug UIs in a single class, they're not much code and it would avoid dealing with multiple files.
